# Generated by Django 5.1.2 on 2024-11-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_storestock_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
